# keep-sorted start
MD004.style = "dash"
MD007.indent = 4
MD007.style = "fixed"
MD041.enabled = false
MD049.style = "underscore"
MD050.style = "asterisk"
MD055.style = "leading-and-trailing"
MD060.enabled = true
MD060.style = "aligned"
MD077.enabled = false
global.line_length = 0
# keep-sorted end
